export type Alignment = "baseline"
    | "first baseline"
    | "last baseline"
    | "start"
    | "start"
    | "center"
    | "end"
    | "flex-start"
    | "flex-end"
    | "left"
    | "right"
    | "safe"
    | "unsafe"
    | "stretch"
    | "space-around"
    | "space-between"
    | "space-evenly";